name: Deploy Frontend

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: deploy
              run: |
                  cd frontend
                  npm install
                  npm deploy
