name: Deploy Frontend

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: deploy
              run: |
                  npm install
                  npm run deploy
              working-directory: ./frontend
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
