name: eslint

on:
  [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: JavaScript Linting
    steps:
      - uses: actions/checkout@v3
      - name: Run linting rules and tests
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm run build
      - run: npm run lint