name: eslint

on:
  push:
    branches: [ origin ]
  pull_request:
    branches: [ origin ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test example
        working-directory: ./example
        run: |
          npm install
          cd backend
          npm install
          cd ../frontend
          nom install cd ..
          npm run lint
